{
 "title": "Homework 5 dashboard",
 "description": "An example dashboard for HW5 of the MLOpsZoomcamp course",
 "time": { "from": "2024-02-29T23:00:00.000Z", "to": "2024-03-31T21:59:59.000Z" },
 "panels": [
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "description": "Wasserstein metric drift of the prediction variable, bound to [0,1]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,prediction_drift FROM hw_metrics "
    }
   ]
  },
  {
   "title": "Prediction standard deviation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,prediction_std FROM hw_metrics "
    }
   ]
  },
  {
   "title": "Number of columns with drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,num_drifted_columns FROM hw_metrics "
    }
   ]
  }
 ]
}